### ISSUE TITLE
Extract build CLI from base plugin to avoid bundling build dependencies

### ISSUE THREAD

**Issue by desandro** [swup/plugin#19]
I recently got snagged including all of TypeScript as part of a front-end package because `@swup/plugin` has `microbundle` as a dependency. It looks like microbundle is used for building assets, rather than as a internal dependency used within `src/`. So, I think its safe to switch it over :)

**Comment by hirasso** [comment]
Hey @desandro , thank you for the heads-up! Actually it looks to me like everything except `swup` should be a `devDependency`.

**Current:**

```json
{
  "dependencies": {
    "@swup/browserslist-config": "^1.0.0",
    "@swup/prettier-config": "^1.0.0",
    "chalk": "^5.2.0",
    "prettier": "^2.7.1",
    "shelljs": "^0.8.5",
    "shelljs-live": "^0.0.5",
    "swup": "^3.0.0"
  }
}
```
**New:**
```json
{
  "devDependencies": {
    "@swup/browserslist-config": "^1.0.0",
    "@swup/prettier-config": "^1.0.0",
    "chalk": "^5.2.0",
    "microbundle": "^0.15.1",
    "prettier": "^2.7.1",
    "shelljs": "^0.8.5",
    "shelljs-live": "^0.0.5"
  },
  "dependencies": {
    "swup": "^3.0.0"
  }
}
```

@gmrchk what do you think?

**Comment by gmrchk** [comment]
Hey, @desandro 👋 big fan of your work! 

The `@swup/plugin` newly includes a [handy CLI](https://github.com/swup/plugin/blob/master/package.json#L26) for managing some parts of plugin development. These require the `microbundle` and more to work, so the dependencies are correct in the current setup.  
However, we've already had some talks internally about that not being ideal and about moving the CLI logic over to `@swup/cli` where it would fit better. This would also make it opt-in to install as your plugin dev dependency, meaning the dependency mess wouldn't be a thing for the end consumer. In the end, `swup` should be the only dependency of `@swup/plugin`, as @hirasso mentioned already, but it will take a bit more work than just switching the deps. 

We'll look into it. Thanks for reporting.

**Comment by daun** [comment]
I'll rename the issue to reflect the required action to resolve this.

**Comment by hirasso** [comment]
What needs to be done to fix this?

**Comment by lubomirblazekcz** [comment]
microbundle also causes bunch of npm WARNs, so separation into devDependencies would be nice
```
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated @babel/plugin-proposal-class-properties@7.12.1: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```

**Comment by daun** [comment]
@lubomirblazekcz We're working on extracting the plugin build CLI into swup's standalone CLI. This should solve the problem by making the installation of the CLI completely optional. Feel free to [track the progress](https://github.com/swup/cli/pull/22) over at the related PR.

**Comment by daun** [comment]
`@swup/plugin` no longer includes dev dependencies like microbundle. We'll now start migrating any official plugins to switch to `@swup/cli` for bundling in the coming days.
