### ISSUE TITLE
`swup-plugin lint` only lints `js` files

### ISSUE THREAD

**Issue by hirasso** [swup/plugin#21]
**Description of the issue**

`swup-plugin lint` should also lint `.ts`, `.mjs`, `.cjs` files.

**How to reproduce the issue**

Run `swup-plugin lint` in a Plugin built in TypeScript

**Comment by daun** [comment]
There's [this trick](https://github.com/prettier/prettier/issues/8233#issuecomment-698884492) we can try implementing.

```sh
npx prettier --write '**/(*.js|.ts)'
```

**Comment by daun** [comment]
Then there's prettier's `--no-error-on-unmatched-pattern` flag, but that just looks silly in comparison I think.

**Comment by hirasso** [comment]
I'm not getting the "No files matching" error  when using `npx prettier 'src/**/*.{js,ts,mjs}' --check`. I'm in a TypeScript project, no `js` files. I think we can safely assume every plugin will have one of the files in the `./src/` folder. Prettier will only complain if it doesn't find **any** match. 

Created a PR #22

**Comment by daun** [comment]
Interesting. It was complaining for missing `*.ts` files even if it found a `*.js` file. Not sure if that has chagned in the meantime.

**Comment by hirasso** [comment]
🤷‍♂️ I only tested it in a ts project. Let's see what happens in js projects now
